### ISSUE TITLE
App stop after select item in Search screen

### ISSUE THREAD

**Issue by khacpv** [sockeqwe/mosby#111]
Hi, today I pull code and tried to run email sample app and see bug:

`
FATAL EXCEPTION: main
                                                                                      Process: com.hannesdorfmann.mosby.sample.mail, PID: 22258
                                                                                      java.lang.ClassCastException: You try to use CastedArrayListLceViewState which takes List<D> as argument but assumes that it's an instance of ArrayList<D>. Howerver, your loaded data is not an ArrayList but it's of type java.util.AbstractList.SubAbstractListRandomAccess which is not supported
                                                                                          at com.hannesdorfmann.mosby.mvp.viewstate.lce.data.CastedArrayListLceViewState.writeToParcel(CastedArrayListLceViewState.java:70)
                                                                                          at android.os.Parcel.writeParcelable(Parcel.java:1368)
                                                                                          at android.os.Parcel.writeValue(Parcel.java:1273)
                                                                                          at android.os.Parcel.writeArrayMapInternal(Parcel.java:649)
                                                                                          at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
                                                                                          at android.os.Bundle.writeToParcel(Bundle.java:1034)
                                                                                          at android.os.Parcel.writeBundle(Parcel.java:674)
                                                                                          at android.support.v4.app.FragmentState.writeToParcel(Fragment.java:138)
                                                                                          at android.os.Parcel.writeTypedArray(Parcel.java:1202)
                                                                                          at android.support.v4.app.FragmentManagerState.writeToParcel(FragmentManager.java:385)
                                                                                          at android.os.Parcel.writeParcelable(Parcel.java:1368)
                                                                                          at android.os.Parcel.writeValue(Parcel.java:1273)
                                                                                          at android.os.Parcel.writeArrayMapInternal(Parcel.java:649)
                                                                                          at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
                                                                                          at android.os.Bundle.writeToParcel(Bundle.java:1034)
                                                                                          at android.os.Parcel.writeBundle(Parcel.java:674)
                                                                                          at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:2930)
                                                                                          at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3402)
                                                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                          at android.os.Looper.loop(Looper.java:211)
                                                                                          at android.app.ActivityThread.main(ActivityThread.java:5373)
                                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
                                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815
`

**Comment by sockeqwe** [comment]
Thanks for reporting, i will have a look at it next week

**Comment by sockeqwe** [comment]
Fixed. #221
