### ISSUE TITLE
Unable to test MvpActivity with Robolectric and Mockito

### ISSUE THREAD

**Issue by tomasznajda** [sockeqwe/mosby#179]
**Mosby Version: 2.0.1
Robolectric Version: 3.1.4
Mockito Version: 2.2.22**

I found a bug when I tried to run Robolectric and Mockito tests.
I am creating a shadow activity of a UserDetailsActivity using Robolectric. After that I am injecting mock of Presenter. When I am trying to call Activity#onCreate() there is an issue with casting my Presenter to ShadowActivity.

Below you can see my test class. UserDetailsActivity extends Mosby's MvpActivity.
```java
@RunWith(RobolectricTestRunner.class)
@Config(constants = BuildConfig.class, sdk = 21)
public class UserDetailsActivityTest {

    @Mock
    private UserDetailsPresenter mPresenter;

    @InjectMocks
    private UserDetailsActivity mActivity;

    @Before
    public void setup() {
        ActivityController<UserDetailsActivity> controller = Robolectric.buildActivity(UserDetailsActivity.class);
        mActivity = controller.get();
        MockitoAnnotations.initMocks(this);
        controller.create();
    }

    @Test
    public void testOnViewCreated_shouldCallPresenterOnViewCreated() {
        Mockito.verify(mPresenter).onViewCreated();
    }
}
```

When the controller.create() is called, the test fails and following cast exception appears:
```ruby
java.lang.ClassCastException: Cannot cast com.mateuszkoslacz.moviper.rxsample.viper.presenter.UserDetailsPresenter$MockitoMock$679472448 to org.robolectric.shadows.ShadowActivity

	at java.lang.invoke.MethodHandleImpl.newClassCastException(MethodHandleImpl.java:361)
	at java.lang.invoke.MethodHandleImpl.castReference(MethodHandleImpl.java:356)
	at android.app.Activity.getWindow(Activity.java)
	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:185)
	at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:525)
	at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:74)
	at com.hannesdorfmann.mosby.mvp.MvpActivity.onCreate(MvpActivity.java:41)
	at com.mateuszkoslacz.moviper.rxsample.viper.view.activity.UserDetailsActivity.onCreate(UserDetailsActivity.java:55)
	at android.app.Activity.performCreate(Activity.java:5933)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:195)
	at org.robolectric.util.ActivityController$1.run(ActivityController.java:126)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:356)
	at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:40)
	at org.robolectric.util.ActivityController.create(ActivityController.java:123)
	at org.robolectric.util.ActivityController.create(ActivityController.java:133)
	at com.mateuszkoslacz.moviper.rxsample.viper.view.activity.UserDetailsActivityTest.setup(UserDetailsActivityTest.java:36)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:245)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:171)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:137)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:119)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

Has anyone encountered this strange issue in which Presenter is casted to ShadowActivity?

**Comment by sockeqwe** [comment]
Thanks for the detailed information. Unfortunately I can't really say whether or not this is an mosby ugg. Could you try to run your Unit Test with a debugger attached and set a breakpoint in `UserDetailsActivity.oncreate()` before calling super.onCreate()? and step into the super method and so on to check where exactly this cast exception comes from.

Thanks

**Comment by tomasznajda** [comment]
Thanks for a quick reply.

I will provide more detailed informations a little bit later, but I guess the answer is in the stacktrace.
The 7th line is from Mosby's MvpActivity.

```ruby
at com.hannesdorfmann.mosby.mvp.MvpActivity.onCreate(MvpActivity.java:41)
```

If it will help, below you can find my UserDetailsActivity#onCreate() method:
```java
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_user_details);
        ButterKnife.bind(this);
        getPresenter().onViewCreated();
    }
```

**Comment by sockeqwe** [comment]
> at com.hannesdorfmann.mosby.mvp.MvpActivity.onCreate(MvpActivity.java:41)

but then I would expect that this will be the root of the stack trace, but actually the cast exceptions seems to happen in 
```
at android.app.Activity.getWindow(Activity.java)
```

Hence I'm asking you to add a debugger and step over the hierarchy

**Comment by mkoslacz** [comment]
It's thrown while trying to go through (or in) this return statement:
```java
    /**
     * Create a {@link android.support.v7.app.AppCompatDelegate} to use with {@code activity}.
     *
     * @param callback An optional callback for AppCompat specific events
     */
    public static AppCompatDelegate create(Activity activity, AppCompatCallback callback) {
        return create(activity, activity.getWindow(), callback);
    }
```
Actually, the arguments of this method looks fine in a debugger:
![zrzut ekranu 2016-11-26 o 11 33 39](https://cloud.githubusercontent.com/assets/7924595/20639747/4824e8ec-b3cc-11e6-8ee9-9f7eecdf9da5.png)

**Comment by sockeqwe** [comment]
Hm, really strange ... At first glance it doesn't seem to be Mosby related ...

Could you test if this error also occurs with support library version `24.x.y`. Maybe it is an issue with robolectric and support library `25.x.y`

**Comment by mkoslacz** [comment]
Hehe, that's what I'm doing already. Will report soon.

**Comment by sockeqwe** [comment]
is this sample project hosted somewhere, so that I could take a closer look at the unit test?

**Comment by mkoslacz** [comment]
Repo: https://github.com/mkoslacz/Moviper 
Branch: rx-tests-rdp 
Test: com.mateuszkoslacz.moviper.rxsample.viper.view.activity.ListingActivityTest#onViewCreated()

Btw, this project is a Mosby VIPER extension. Mentioned sample has grown too much, it will probably be extracted to the architecture showcasing project.

**Comment by mkoslacz** [comment]
Previously, the test was run using Robolectric in the sdk 21 mode, while the project was targeting the sdk 25. After changing both sdks to 23 (and applying [this](https://github.com/robolectric/robolectric/issues/1932) hack) nothing has changed. 

The interesting thing is that AS keeps routing me to the appcompat-v7-25.0.0 files when navigating through a thrown exception stack.

**Comment by mkoslacz** [comment]
> in fact it looks like it's a problem with Robolectric and Mockito, it has nothing to do with Glide. 

This problem can be tracked in the mentioned issue on Robolectric github: [#2726](https://github.com/robolectric/robolectric/issues/2726).

You have shown some interest in diving in this problem, but if you have abandoned it, this issue should be probably closed.

**Comment by sockeqwe** [comment]
I think this should be fixed with Robolectric 3.2.1

**Comment by sockeqwe** [comment]
Fix is available in latest snapshot

**Comment by mkoslacz** [comment]
Well, yep, we realized that the problem occurs when you try to inject mocks using Mockito `@InjectMocks` on the Robolectric shadows. One can workaround it by simple setting presenter using `MvpDelegateCallback#setPresenter(MvpPresenter)` on any of the Mosby views. Moreover, mentioned Robolectric snapshot fixes this issue allowing using `@InjectMocks` on Robolectric objects. Sorry for not updating this thread.
