### ISSUE TITLE
Issue with Mosby SavedState

### ISSUE THREAD

**Issue by sockeqwe** [sockeqwe/mosby#190]
Disable Keep Activity in Developer settings.

```
Class not found when unmarshalling: android.support.v7.widget.Toolbar$SavedState
          java.lang.ClassNotFoundException: android.support.v7.widget.Toolbar$SavedState
              at java.lang.Class.classForName(Native Method)
              at java.lang.Class.forName(Class.java:324)
              at android.os.Parcel.readParcelableCreator(Parcel.java:2383)
              at android.os.Parcel.readParcelable(Parcel.java:2337)
              at android.view.AbsSavedState.<init>(AbsSavedState.java:57)
              at android.view.View$BaseSavedState.<init>(View.java:21451)
              at com.hannesdorfmann.mosby3.MosbySavedState.<init>(MosbySavedState.java:49)
              at com.hannesdorfmann.mosby3.MosbySavedState$1.createFromParcel(MosbySavedState.java:34)
              at com.hannesdorfmann.mosby3.MosbySavedState$1.createFromParcel(MosbySavedState.java:32)
              at android.os.Parcel.readParcelable(Parcel.java:2346)
              at android.os.Parcel.readValue(Parcel.java:2243)
              at android.os.Parcel.readSparseArrayInternal(Parcel.java:2653)
              at android.os.Parcel.readSparseArray(Parcel.java:1946)
              at android.os.Parcel.readValue(Parcel.java:2300)
              at android.os.Parcel.readArrayMapInternal(Parcel.java:2592)
              at android.os.BaseBundle.unparcel(BaseBundle.java:221)
              at android.os.Bundle.getSparseParcelableArray(Bundle.java:856)
              at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1207)
              at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1467)
              at android.support.v4.app.FragmentManagerImpl.onCreateView(FragmentManager.java:3384)
              at android.support.v4.app.FragmentController.onCreateView(FragmentController.java:120)
              at android.support.v4.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:378)
              at android.support.v4.app.BaseFragmentActivityHoneycomb.onCreateView(BaseFragmentActivityHoneycomb.java:33)
              at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:79)
              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:754)
              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
              at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
              at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
              at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
              at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
              at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
              at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
              at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
              at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:288)
              at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:143)
              at com.hannesdorfmann.mosby3.sample.mvi.MainActivity.onCreate(MainActivity.java:57)
              at android.app.Activity.performCreate(Activity.java:6237)
              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
              at android.app.ActivityThread.-wrap11(ActivityThread.java)
              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
              at android.os.Handler.dispatchMessage(Handler.java:102)
              at android.os.Looper.loop(Looper.java:148)
              at android.app.ActivityThread.main(ActivityThread.java:5417)
              at java.lang.reflect.Method.invoke(Native Method)
              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
           Caused by: java.lang.ClassNotFoundException: android.support.v7.widget.Toolbar$SavedState
              at java.lang.Class.classForName(Native Method)
              at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
              at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
              at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
              at java.lang.Class.classForName(Native Method) 
              at java.lang.Class.forName(Class.java:324) 
              at android.os.Parcel.readParcelableCreator(Parcel.java:2383) 
              at android.os.Parcel.readParcelable(Parcel.java:2337) 
              at android.view.AbsSavedState.<init>(AbsSavedState.java:57) 
              at android.view.View$BaseSavedState.<init>(View.java:21451) 
              at com.hannesdorfmann.mosby3.MosbySavedState.<init>(MosbySavedState.java:49) 
              at com.hannesdorfmann.mosby3.MosbySavedState$1.createFromParcel(MosbySavedState.java:34) 
              at com.hannesdorfmann.mosby3.MosbySavedState$1.createFromParcel(MosbySavedState.java:32) 
              at android.os.Parcel.readParcelable(Parcel.java:2346) 
              at android.os.Parcel.readValue(Parcel.java:2243) 
              at android.os.Parcel.readSparseArrayInternal(Parcel.java:2653) 
              at android.os.Parcel.readSparseArray(Parcel.java:1946) 
              at android.os.Parcel.readValue(Parcel.java:2300) 
              at android.os.Parcel.readArrayMapInternal(Parcel.java:2592) 
              at android.os.BaseBundle.unparcel(BaseBundle.java:221) 
              at android.os.Bundle.getSparseParcelableArray(Bundle.java:856) 
              at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1207) 
              at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1467) 
              at android.support.v4.app.FragmentManagerImpl.onCreateView(FragmentManager.java:3384) 
              at android.support.v4.app.FragmentController.onCreateView(FragmentController.java:120) 
              at android.support.v4.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:378) 
              at android.support.v4.app.BaseFragmentActivityHoneycomb.onCreateView(BaseFragmentActivityHoneycomb.java:33) 
              at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:79) 
              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:754) 
              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
              at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
              at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
              at android.view.LayoutInflater.rInflate(LayoutInflater.java:838) 
              at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
              at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
              at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
              at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
              at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:288) 
              at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:143) 
              at com.hannesdorfmann.mosby3.sample.mvi.MainActivity.onCreate(MainActivity.java:57) 
              at android.app.Activity.performCreate(Activity.java:6237) 
              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
              at android.app.ActivityThread.-wrap11(ActivityThread.java) 
              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
              at android.os.Handler.dispatchMessage(Handler.java:102) 
              at android.os.Looper.loop(Looper.java:148) 
              at android.app.ActivityThread.main(ActivityThread.java:5417) 
              at java.lang.reflect.Method.invoke(Native Method) 
              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
           Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```

**Comment by sockeqwe** [comment]
Turns out that this is actually not a Bug of Mosby, but rather a Bug of support lib / fragments with recreation and class loader. It only affects the mvi-sample.

https://code.google.com/p/android/issues/detail?id=196430

**Comment by sockeqwe** [comment]
https://code.google.com/p/android/issues/detail?id=232471
