### ISSUE TITLE
Error in Mail Sample if i try to write a new Mail on a 4.3 Android

### ISSUE THREAD

**Issue by HowardSchmaeu** [sockeqwe/mosby#58]
Hey Hannes,

if i try to start your Mail Sample on a Android 4.3 Version (Genymotion Google Nexus 4 - API 18) the i got an Error if i try to send a Mail. If i try the same on a 5.0 (also Genymotion Google Nexus 4 - API 21)... everything is fine...
I got this:

6-25 17:25:12.703    2221-2221/com.hannesdorfmann.mosby.sample.mail E/Event﹕ Could not dispatch event: class com.hannesdorfmann.mosby.sample.mail.model.event.MailSentEvent to subscribing class class com.hannesdorfmann.mosby.sample.mail.write.WritePresenter
    java.lang.NoSuchMethodError: com.hannesdorfmann.mosby.sample.mail.write.WriteActivity.finishAfterTransition
            at com.hannesdorfmann.mosby.sample.mail.write.WriteActivity.finishBecauseSuccessful(WriteActivity.java:187)
            at com.hannesdorfmann.mosby.sample.mail.write.WritePresenter.onEventMainThread(WritePresenter.java:54)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at de.greenrobot.event.EventBus.invokeSubscriber(EventBus.java:498)
            at de.greenrobot.event.EventBus.invokeSubscriber(EventBus.java:492)
            at de.greenrobot.event.HandlerPoster.handleMessage(HandlerPoster.java:67)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5103)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by sockeqwe** [comment]
Oh yeah I see ... I forgot to check for SDK 21 ... i will fix that this
evening ...

A quick fix is in
finishBecauseSuccessful(WriteActivity.java:187) : replace
finishAfterTransition() just with finish() to make it work on API < 21

HowardSchmaeu <notifications@github.com> schrieb am Do., 25. Juni 2015
17:32:
