### ISSUE TITLE
Mail Sample: Dialog AppComat Bug

### ISSUE THREAD

**Issue by sockeqwe** [sockeqwe/mosby#78]
There is a bug in the support v7 23.0.0 library with dialogs. Will be fixed in next support library.

Android issue tracker
https://code.google.com/p/android/issues/detail?id=183186

android.util.AndroidRuntimeException: Window feature must be requested before adding content
            at android.support.v7.app.AppCompatDelegateImplV7.throwFeatureRequestIfSubDecorInstalled(AppCompatDelegateImplV7.java:1584)
            at android.support.v7.app.AppCompatDelegateImplV7.requestWindowFeature(AppCompatDelegateImplV7.java:509)
            at android.support.v7.app.AppCompatDelegateImplBase.onCreate(AppCompatDelegateImplBase.java:117)
            at android.support.v7.app.AppCompatDelegateImplV7.onCreate(AppCompatDelegateImplV7.java:148)
            at android.support.v7.app.AppCompatDialog.onCreate(AppCompatDialog.java:60)
            at android.app.Dialog.dispatchOnCreate(Dialog.java:373)
            at android.app.Dialog.show(Dialog.java:274)
            at android.support.v4.app.DialogFragment.onStart(DialogFragment.java:406)
            at com.hannesdorfmann.mosby.sample.mail.statistics.StatisticsDialog.onStart(StatisticsDialog.java:86)
            at android.support.v4.app.Fragment.performStart(Fragment.java:1986)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1051)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1197)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1562)
            at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:483)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by sockeqwe** [comment]
Has been fixed in support library 23.0.1
